ifeq ($(CONFIG_OF),y)

ifeq ($(CONFIG_MACH_MSM8974_B1_KR),y)
DTS_TARGET := msm8974-b1-kr
endif

ifeq ($(CONFIG_MACH_MSM8974_B1W),y)
DTS_TARGET := msm8974-b1w
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_ATT),y)
DTS_TARGET := msm8974-g2-att
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_CA),y)
DTS_TARGET := msm8974-g2-ca
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_DCM),y)
DTS_TARGET := msm8974-g2-dcm
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_EVB),y)
DTS_TARGET := msm8974-g2-evb
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_KDDI),y)
DTS_TARGET := msm8974-g2-kddi
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_KR),y)
DTS_TARGET := msm8974-g2-kr
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_OPEN_AME),y)
DTS_TARGET := msm8974-g2-open_ame
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_OPEN_COM),y)
DTS_TARGET := msm8974-g2-open_com
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_OPT_AU),y)
DTS_TARGET := msm8974-g2-opt_au
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_SPR),y)
DTS_TARGET := msm8974-g2-spr
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_TEL_AU),y)
DTS_TARGET := msm8974-g2-tel_au
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_TMO_US),y)
DTS_TARGET := msm8974-g2-tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8974_G2_VZW),y)
DTS_TARGET := msm8974-g2-vzw
endif

ifeq ($(CONFIG_MACH_MSM8974_DZNY_DCM),y)
DTS_TARGET := msm8974pro-dzny-dcm
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_ACG_US),y)
DTS_TARGET := msm8974pro-g3-acg_us
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_ATT),y)
DTS_TARGET := msm8974pro-g3-att
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_ATT_BRCM),y)
DTS_TARGET := msm8974pro-g3-att-brcm
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_CA),y)
DTS_TARGET := msm8974pro-g3-ca
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_CLR_PR),y)
DTS_TARGET := msm8974pro-g3-clr_pr
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_CLR_PR_BRCM),y)
DTS_TARGET := msm8974pro-g3-clr_pr-brcm
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_CN),y)
DTS_TARGET := msm8974pro-g3-cn
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_GLOBAL_COM),y)
DTS_TARGET := msm8974pro-g3-global_com
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_GLOBAL_COM_BRCM),y)
DTS_TARGET := msm8974pro-g3-global_com-brcm
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_KDDI),y)
DTS_TARGET := msm8974pro-g3-kddi
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_KDDI_EVB),y)
DTS_TARGET := msm8974pro-g3-kddi-evb
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_KR),y)
DTS_TARGET := msm8974pro-g3-kr
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_LGU_EVB),y)
DTS_TARGET := msm8974pro-g3-kr-evb
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_LRA),y)
DTS_TARGET := msm8974pro-g3-lra
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_LRA_BRCM),y)
DTS_TARGET := msm8974pro-g3-lra-brcm
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_SPR_US),y)
DTS_TARGET := msm8974pro-g3-spr_us
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_TMO_US),y)
DTS_TARGET := msm8974pro-g3-tmo_us
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_USC_US),y)
DTS_TARGET := msm8974pro-g3-usc_us
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_VZW),y)
DTS_TARGET := msm8974pro-g3-vzw
endif

ifeq ($(CONFIG_MACH_MSM8974_G3_VZW_BRCM),y)
DTS_TARGET := msm8974pro-g3-vzw-brcm
endif

ifeq ($(CONFIG_MACH_MSM8974_T1_ATT),y)
DTS_TARGET := msm8974-t1-att
endif

ifeq ($(CONFIG_MACH_MSM8974_T1LTE_GLOBAL_COM),y)
DTS_TARGET := msm8974-t1-global_com
endif

ifeq ($(CONFIG_MACH_MSM8974_T1_USC),y)
DTS_TARGET := msm8974-t1-usc
endif

ifeq ($(CONFIG_MACH_MSM8974_T1WIFI_GLOBAL_COM),y)
DTS_TARGET := msm8974-t1wifi-global_com
endif

ifeq ($(CONFIG_MACH_MSM8974_T1WIFIN_GLOBAL_COM),y)
DTS_TARGET := msm8974-t1wifin-global_com
endif

ifeq ($(CONFIG_MACH_MSM8974_TIGERS_KR),y)
DTS_TARGET := msm8974-tigers-kr
endif

ifeq ($(CONFIG_MACH_MSM8974_VU3_KR),y)
DTS_TARGET := msm8974-vu3-kr
endif

ifeq ($(CONFIG_MACH_MSM8974_Z_ATT_US),y)
DTS_TARGET := msm8974-z-att
endif

ifeq ($(CONFIG_MACH_MSM8974_Z_CA),y)
DTS_TARGET := msm8974-z-ca
endif

ifeq ($(CONFIG_MACH_MSM8974_Z_CTC_CN),y)
DTS_TARGET := msm8974-z-ctc
endif

ifeq ($(CONFIG_MACH_MSM8974_Z_KDDI),y)
DTS_TARGET := msm8974-z-kddi
endif

ifeq ($(CONFIG_MACH_MSM8974_Z_KR),y)
DTS_TARGET := msm8974-z-kr
endif

ifeq ($(CONFIG_MACH_MSM8974_Z_OPEN_COM),y)
DTS_TARGET := msm8974-z-open_com
endif

ifeq ($(CONFIG_MACH_MSM8974_Z_SPR),y)
DTS_TARGET := msm8974-z-spr
endif

ifeq ($(CONFIG_MACH_MSM8974_Z_TMO_US),y)
DTS_TARGET := msm8974-z-tmo
endif

ALL_DTS := $(notdir $(wildcard echo $(srctree)/$(src)/$(DTS_TARGET)/*.dts))
dtb-y += $(patsubst %.dts,%.dtb,$(ALL_DTS))

DTB_NAMES := $(subst $\",,$(CONFIG_BUILD_ARM_APPENDED_DTB_IMAGE_NAMES))
ifneq ($(DTB_NAMES),)
DTB_LIST := $(addsuffix .dtb,$(DTB_NAMES))
else
DTB_LIST := $(dtb-y)
endif

targets += dtbs
targets += $(addprefix ../, $(DTB_LIST))
endif

$(obj)/../%.dtb: $(src)/$(DTS_TARGET)/%.dts FORCE
	$(call if_changed_dep,dtc)
dtbs: $(addprefix $(obj)/../,$(DTB_LIST))

clean-files := *.dtb
